export const servicesData = {
  'web-development': {
    title: 'Web Development',
    subtitle: 'Modern Web Solutions',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-code',
    overview: 'I build high-performance, responsive websites using cutting-edge technologies. From simple landing pages to complex web applications, every project is crafted with clean code and optimal user experience.',
    features: [
      { title: 'Responsive Design', desc: 'Websites that look perfect on all devices.' },
      { title: 'Performance Optimized', desc: 'Lightning-fast load times with optimized assets.' },
      { title: 'SEO Friendly', desc: 'Built with search engine best practices.' },
      { title: 'Scalable Architecture', desc: 'Future-proof code that grows with your business.' },
      { title: 'Modern Tech Stack', desc: 'Built with React, Next.js, Node.js.' },
      { title: 'Ongoing Support', desc: 'Post-launch maintenance and updates.' },
    ],
    techStack: ['React', 'Next.js', 'Node.js', 'TypeScript', 'Tailwind CSS', 'MongoDB', 'PostgreSQL', 'GraphQL'],
    process: [
      { step: '01', title: 'Discovery', desc: 'Understanding your goals and requirements.' },
      { step: '02', title: 'Planning', desc: 'Creating wireframes and architecture.' },
      { step: '03', title: 'Development', desc: 'Building with clean, maintainable code.' },
      { step: '04', title: 'Testing', desc: 'Rigorous testing across devices.' },
      { step: '05', title: 'Launch', desc: 'Deploying to production.' },
      { step: '06', title: 'Support', desc: 'Ongoing maintenance and updates.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$999', features: ['5 Pages', 'Responsive Design', 'Contact Form', 'Basic SEO', '1 Month Support'] },
      { plan: 'Professional', price: '$2,499', features: ['10 Pages', 'Custom Design', 'CMS Integration', 'Advanced SEO', 'E-commerce Ready', '3 Months Support'] },
      { plan: 'Enterprise', price: '$4,999', features: ['Unlimited Pages', 'Custom Web App', 'Admin Dashboard', 'API Integration', 'Priority Support', '12 Months Support'] },
    ],
  },
  'mobile-apps': {
    title: 'Mobile Apps',
    subtitle: 'Cross-Platform Mobile Solutions',
    image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-mobile-screen',
    overview: 'I create beautiful, performant mobile applications that work seamlessly across iOS and Android platforms using React Native and Flutter frameworks.',
    features: [
      { title: 'Cross-Platform', desc: 'One codebase for iOS and Android.' },
      { title: 'Native Performance', desc: 'Smooth animations and fast response.' },
      { title: 'Offline Support', desc: 'Apps that work without internet.' },
      { title: 'Push Notifications', desc: 'Engage users with timely notifications.' },
      { title: 'App Store Ready', desc: 'Full App Store and Google Play support.' },
      { title: 'Regular Updates', desc: 'Continuous improvements and features.' },
    ],
    techStack: ['React Native', 'Flutter', 'Firebase', 'Redux', 'Node.js', 'REST APIs', 'GraphQL'],
    process: [
      { step: '01', title: 'Concept', desc: 'Defining app purpose and user flows.' },
      { step: '02', title: 'Design', desc: 'Creating UI/UX designs.' },
      { step: '03', title: 'Development', desc: 'Building core functionality.' },
      { step: '04', title: 'Testing', desc: 'Testing on multiple devices.' },
      { step: '05', title: 'Deploy', desc: 'Publishing to app stores.' },
      { step: '06', title: 'Maintain', desc: 'Updates and improvements.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$1,499', features: ['Basic App', 'iOS & Android', 'Simple UI', 'Basic Features', '1 Month Support'] },
      { plan: 'Business', price: '$3,999', features: ['Advanced App', 'Custom UI', 'API Integration', 'Push Notifications', 'Analytics', '3 Months Support'] },
      { plan: 'Premium', price: '$7,999', features: ['Complex App', 'Premium UI/UX', 'Advanced Features', 'Admin Panel', 'Priority Support', '12 Months Support'] },
    ],
  },
  'landing-page': {
    title: 'Landing Page Design',
    subtitle: 'High-Converting Landing Pages',
    image: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-paint-brush',
    overview: 'I design and develop high-converting landing pages that capture leads and drive sales. Each page is optimized for maximum conversion with compelling copy and strategic CTAs.',
    features: [
      { title: 'Conversion Focused', desc: 'Designed to maximize lead generation and sales.' },
      { title: 'A/B Testing Ready', desc: 'Built for split testing to optimize performance.' },
      { title: 'Fast Loading', desc: 'Optimized for sub-2 second load times.' },
      { title: 'Mobile Optimized', desc: 'Perfect display on all devices and screens.' },
      { title: 'SEO Ready', desc: 'On-page SEO optimized for search visibility.' },
      { title: 'Analytics Integration', desc: 'Track every click and conversion.' },
    ],
    techStack: ['HTML', 'CSS', 'JavaScript', 'React', 'Tailwind CSS', 'Google Analytics', 'A/B Testing'],
    process: [
      { step: '01', title: 'Research', desc: 'Understanding your audience and goals.' },
      { step: '02', title: 'Wireframe', desc: 'Designing the page structure.' },
      { step: '03', title: 'Copywriting', desc: 'Crafting compelling content.' },
      { step: '04', title: 'Design', desc: 'Creating visually appealing layout.' },
      { step: '05', title: 'Development', desc: 'Building responsive landing page.' },
      { step: '06', title: 'Optimize', desc: 'Testing and improving conversions.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$499', features: ['1 Landing Page', 'Responsive Design', 'Contact Form', 'Basic Analytics', '1 Week Support'] },
      { plan: 'Professional', price: '$999', features: ['3 Landing Pages', 'A/B Testing Setup', 'Advanced Analytics', 'Email Integration', '1 Month Support'] },
      { plan: 'Enterprise', price: '$1,999', features: ['Unlimited Pages', 'Full Optimization', 'CRM Integration', 'Heatmaps', 'Priority Support'] },
    ],
  },
  'responsive-apps': {
    title: 'Responsive Web Apps',
    subtitle: 'Progressive Web Applications',
    image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-mobile-screen',
    overview: 'I build Progressive Web Applications (PWAs) that provide native app-like experiences directly in the browser, working flawlessly across all devices and platforms.',
    features: [
      { title: 'Offline Support', desc: 'Work without internet connection.' },
      { title: 'Push Notifications', desc: 'Engage users with timely updates.' },
      { title: 'App-like Experience', desc: 'Smooth animations and navigation.' },
      { title: 'Installable', desc: 'Add to home screen functionality.' },
      { title: 'Cross-Platform', desc: 'Works on all devices and browsers.' },
      { title: 'Auto Updates', desc: 'Always up-to-date without app store.' },
    ],
    techStack: ['React', 'PWA', 'Tailwind', 'Service Workers', 'IndexedDB', 'Web APIs'],
    process: [
      { step: '01', title: 'Planning', desc: 'Defining app features and scope.' },
      { step: '02', title: 'Design', desc: 'Creating responsive layouts.' },
      { step: '03', title: 'Development', desc: 'Building core functionality.' },
      { step: '04', title: 'PWA Setup', desc: 'Adding service workers and manifest.' },
      { step: '05', title: 'Testing', desc: 'Testing across devices and browsers.' },
      { step: '06', title: 'Deploy', desc: 'Launching with monitoring.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$1,499', features: ['Basic PWA', 'Offline Support', 'Responsive Design', '1 Month Support'] },
      { plan: 'Professional', price: '$3,499', features: ['Advanced PWA', 'Push Notifications', 'Background Sync', 'Analytics', '3 Months Support'] },
      { plan: 'Enterprise', price: '$6,499', features: ['Complex PWA', 'Full Features', 'Admin Dashboard', 'API Integration', 'Priority Support'] },
    ],
  },
  'ui-libraries': {
    title: 'UI Component Libraries',
    subtitle: 'Scalable Design Systems',
    image: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-palette',
    overview: 'I create reusable, scalable component libraries and design systems that ensure consistent brand experience across all your digital products.',
    features: [
      { title: 'Reusable Components', desc: 'Build once, use everywhere approach.' },
      { title: 'Consistent Design', desc: 'Uniform look across all applications.' },
      { title: 'Documentation Ready', desc: 'Full Storybook documentation included.' },
      { title: 'Accessibility', desc: 'WCAG compliant components.' },
      { title: 'Theme Support', desc: 'Light/dark mode and custom themes.' },
      { title: 'TypeScript Ready', desc: 'Full type safety and autocomplete.' },
    ],
    techStack: ['Storybook', 'React', 'Design Systems', 'TypeScript', 'Tailwind', 'Testing Library'],
    process: [
      { step: '01', title: 'Audit', desc: 'Analyzing existing components.' },
      { step: '02', title: 'Design', desc: 'Creating design tokens and guidelines.' },
      { step: '03', title: 'Build', desc: 'Developing component library.' },
      { step: '04', title: 'Document', desc: 'Writing comprehensive documentation.' },
      { step: '05', title: 'Test', desc: 'Testing all components thoroughly.' },
      { step: '06', title: 'Integrate', desc: 'Implementing across projects.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$1,999', features: ['20 Components', 'Basic Documentation', 'Design Tokens', '1 Month Support'] },
      { plan: 'Professional', price: '$4,999', features: ['50 Components', 'Full Documentation', 'Storybook Setup', 'Theme System', '3 Months Support'] },
      { plan: 'Enterprise', price: '$9,999', features: ['Unlimited Components', 'Complete Design System', 'Custom Themes', 'Team Training', 'Priority Support'] },
    ],
  },
  'graphql-api': {
    title: 'GraphQL API Solutions',
    subtitle: 'Flexible Data Querying',
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-plug',
    overview: 'I build flexible and efficient GraphQL APIs that allow clients to request exactly the data they need, reducing bandwidth and improving performance.',
    features: [
      { title: 'Efficient Queries', desc: 'Request only needed data fields.' },
      { title: 'Type Safety', desc: 'Strongly typed schema definitions.' },
      { title: 'Real-time Support', desc: 'Subscriptions for live data updates.' },
      { title: 'Batching', desc: 'Combine multiple queries efficiently.' },
      { title: 'Introspection', desc: 'Self-documenting API capabilities.' },
      { title: 'Caching', desc: 'Optimized with Apollo Client caching.' },
    ],
    techStack: ['GraphQL', 'Apollo', 'MongoDB', 'PostgreSQL', 'Node.js', 'TypeScript'],
    process: [
      { step: '01', title: 'Schema Design', desc: 'Defining types and relationships.' },
      { step: '02', title: 'Resolvers', desc: 'Implementing data fetching logic.' },
      { step: '03', title: 'Security', desc: 'Adding auth and rate limiting.' },
      { step: '04', title: 'Testing', desc: 'Testing queries and mutations.' },
      { step: '05', title: 'Documentation', desc: 'Auto-generating API docs.' },
      { step: '06', title: 'Deploy', desc: 'Launching with monitoring.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$1,499', features: ['10 Types', 'Basic Queries', 'Documentation', '1 Month Support'] },
      { plan: 'Professional', price: '$3,999', features: ['50 Types', 'Subscriptions', 'Advanced Caching', 'Auth Integration', '3 Months Support'] },
      { plan: 'Enterprise', price: '$7,499', features: ['Unlimited Types', 'Microservices', 'Full Security', 'Load Testing', 'Priority Support'] },
    ],
  },
  'auth-systems': {
    title: 'Authentication Systems',
    subtitle: 'Secure Login Solutions',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-shield-halved',
    overview: 'I implement secure authentication systems with JWT, OAuth2, and social login integrations. Your users data stays protected with industry-standard security practices.',
    features: [
      { title: 'JWT Authentication', desc: 'Secure token-based authentication.' },
      { title: 'OAuth2 Integration', desc: 'Google, GitHub, Facebook login.' },
      { title: 'Role-Based Access', desc: 'Granular permission controls.' },
      { title: '2FA Support', desc: 'Two-factor authentication ready.' },
      { title: 'Password Reset', desc: 'Secure password recovery flow.' },
      { title: 'Session Management', desc: 'Track and manage user sessions.' },
    ],
    techStack: ['JWT', 'OAuth2', 'Passport.js', 'Node.js', 'Redis', 'PostgreSQL'],
    process: [
      { step: '01', title: 'Planning', desc: 'Defining auth requirements.' },
      { step: '02', title: 'Setup', desc: 'Configuring auth providers.' },
      { step: '03', title: 'Implementation', desc: 'Building auth endpoints.' },
      { step: '04', title: 'Security', desc: 'Adding security measures.' },
      { step: '05', title: 'Testing', desc: 'Penetration testing and QA.' },
      { step: '06', title: 'Deploy', desc: 'Launching with monitoring.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$799', features: ['JWT Auth', 'Email/Password', 'Basic Roles', '1 Month Support'] },
      { plan: 'Professional', price: '$1,999', features: ['OAuth2 Social Login', '2FA Setup', 'Advanced Roles', 'Session Management', '3 Months Support'] },
      { plan: 'Enterprise', price: '$3,999', features: ['Full Auth Suite', 'SSO Integration', 'Custom Security', 'Compliance Ready', 'Priority Support'] },
    ],
  },
  'microservices': {
    title: 'Microservices Architecture',
    subtitle: 'Scalable Backend Systems',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-cloud',
    overview: 'I design and implement scalable microservices architectures using Docker and Kubernetes, enabling your applications to handle millions of requests efficiently.',
    features: [
      { title: 'Scalability', desc: 'Scale individual services independently.' },
      { title: 'Resilience', desc: 'Fault isolation between services.' },
      { title: 'Docker Containers', desc: 'Consistent deployment environments.' },
      { title: 'Kubernetes', desc: 'Automated orchestration and scaling.' },
      { title: 'Message Queues', desc: 'Async communication with RabbitMQ/Kafka.' },
      { title: 'Monitoring', desc: 'Full observability with logs and metrics.' },
    ],
    techStack: ['Docker', 'Kubernetes', 'RabbitMQ', 'Node.js', 'PostgreSQL', 'Redis', 'Prometheus'],
    process: [
      { step: '01', title: 'Analysis', desc: 'Identifying service boundaries.' },
      { step: '02', title: 'Design', desc: 'Architecting service communication.' },
      { step: '03', title: 'Development', desc: 'Building individual services.' },
      { step: '04', title: 'Containerization', desc: 'Dockerizing all services.' },
      { step: '05', title: 'Orchestration', desc: 'Setting up Kubernetes.' },
      { step: '06', title: 'Monitoring', desc: 'Observability and alerting.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$2,499', features: ['3 Microservices', 'Docker Setup', 'Basic Monitoring', '1 Month Support'] },
      { plan: 'Business', price: '$5,999', features: ['10 Microservices', 'Kubernetes Setup', 'CI/CD Pipeline', 'Message Queues', '3 Months Support'] },
      { plan: 'Enterprise', price: '$12,999', features: ['Unlimited Services', 'Full Orchestration', 'Advanced Security', '24/7 Monitoring', 'Priority Support'] },
    ],
  },
  'ai-chatbot': {
    title: 'AI Chatbot Development',
    subtitle: 'Intelligent Conversational AI',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-robot',
    overview: 'I build intelligent chatbots powered by GPT and custom-trained models that provide human-like conversations for customer support, lead generation, and more.',
    features: [
      { title: 'GPT Powered', desc: 'Leveraging latest GPT models.' },
      { title: 'Custom Training', desc: 'Trained on your business data.' },
      { title: 'Multi-Platform', desc: 'Website, WhatsApp, Telegram, Slack.' },
      { title: 'Context Memory', desc: 'Remembers conversation history.' },
      { title: 'Analytics', desc: 'Track conversations and insights.' },
      { title: 'Human Handoff', desc: 'Seamless transfer to human agents.' },
    ],
    techStack: ['GPT', 'LangChain', 'Python', 'Node.js', 'Vector DB', 'REST APIs'],
    process: [
      { step: '01', title: 'Strategy', desc: 'Defining chatbot use cases.' },
      { step: '02', title: 'Training', desc: 'Training on your business data.' },
      { step: '03', title: 'Development', desc: 'Building chatbot logic.' },
      { step: '04', title: 'Integration', desc: 'Connecting to platforms.' },
      { step: '05', title: 'Testing', desc: 'Quality assurance and tuning.' },
      { step: '06', title: 'Deploy', desc: 'Launching with monitoring.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$1,999', features: ['Basic Chatbot', 'GPT Integration', 'Web Embed', '1 Month Support'] },
      { plan: 'Professional', price: '$4,999', features: ['Advanced Chatbot', 'Custom Training', 'Multi-Platform', 'Analytics', '3 Months Support'] },
      { plan: 'Enterprise', price: '$9,999', features: ['Enterprise Chatbot', 'Full Customization', 'All Platforms', '24/7 Support', 'Priority Service'] },
    ],
  },
  'llm-integration': {
    title: 'LLM Integration',
    subtitle: 'Large Language Model Solutions',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-brain',
    overview: 'I integrate Large Language Models (LLMs) like GPT, Claude, and Gemini into your business workflows for content generation, analysis, and automation.',
    features: [
      { title: 'Multi-Model Support', desc: 'GPT, Claude, Gemini integration.' },
      { title: 'Fine-tuning', desc: 'Custom model training on your data.' },
      { title: 'RAG Systems', desc: 'Retrieval-Augmented Generation.' },
      { title: 'Prompt Engineering', desc: 'Optimized prompts for best results.' },
      { title: 'Cost Optimization', desc: 'Efficient token usage strategies.' },
      { title: 'API Integration', desc: 'Seamless backend integration.' },
    ],
    techStack: ['OpenAI', 'Claude', 'Fine-tuning', 'LangChain', 'Pinecone', 'Python'],
    process: [
      { step: '01', title: 'Assessment', desc: 'Identifying LLM use cases.' },
      { step: '02', title: 'Selection', desc: 'Choosing the right models.' },
      { step: '03', title: 'Integration', desc: 'Implementing API connections.' },
      { step: '04', title: 'Optimization', desc: 'Fine-tuning and prompt engineering.' },
      { step: '05', title: 'Testing', desc: 'Evaluating output quality.' },
      { step: '06', title: 'Deploy', desc: 'Production deployment.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$1,499', features: ['1 LLM Integration', 'Basic Prompts', 'API Setup', '1 Month Support'] },
      { plan: 'Professional', price: '$4,499', features: ['3 LLM Models', 'Fine-tuning', 'RAG Setup', 'Prompt Optimization', '3 Months Support'] },
      { plan: 'Enterprise', price: '$8,999', features: ['Unlimited Models', 'Full Customization', 'Advanced RAG', 'Cost Optimization', 'Priority Support'] },
    ],
  },
  'workflow-automation': {
    title: 'Workflow Automation',
    subtitle: 'Smart Process Automation',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-wand-magic-sparkles',
    overview: 'I automate repetitive tasks and business processes using n8n, Make.com, Zapier, and custom scripts, saving you hours of manual work every week.',
    features: [
      { title: 'No-Code Automation', desc: 'Visual workflow builders.' },
      { title: 'Custom Scripts', desc: 'Python/Node.js for complex logic.' },
      { title: 'Multi-App Integration', desc: 'Connect 1000+ apps seamlessly.' },
      { title: 'Error Handling', desc: 'Robust error recovery mechanisms.' },
      { title: 'Scheduled Tasks', desc: 'Automated recurring workflows.' },
      { title: 'Real-time Triggers', desc: 'Instant workflow activation.' },
    ],
    techStack: ['n8n', 'Make.com', 'Zapier', 'Python', 'Node.js', 'Webhooks', 'APIs'],
    process: [
      { step: '01', title: 'Audit', desc: 'Identifying automation opportunities.' },
      { step: '02', title: 'Design', desc: 'Mapping workflow processes.' },
      { step: '03', title: 'Build', desc: 'Creating automation workflows.' },
      { step: '04', title: 'Test', desc: 'Testing with sample data.' },
      { step: '05', title: 'Document', desc: 'Creating workflow documentation.' },
      { step: '06', title: 'Monitor', desc: 'Tracking and optimizing.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$599', features: ['3 Automations', 'Basic Workflows', 'Email Notifications', '1 Month Support'] },
      { plan: 'Professional', price: '$1,499', features: ['10 Automations', 'Advanced Logic', 'Multi-App Integration', 'Error Handling', '3 Months Support'] },
      { plan: 'Enterprise', price: '$3,499', features: ['Unlimited Automations', 'Custom Scripts', 'Full Integration', 'Priority Support', 'Dedicated Manager'] },
    ],
  },
  'ai-agents': {
    title: 'AI Agent Development',
    subtitle: 'Autonomous AI Solutions',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-microchip',
    overview: 'I build autonomous AI agents that can reason, plan, and execute complex tasks independently using frameworks like AutoGPT, CrewAI, and LangGraph.',
    features: [
      { title: 'Autonomous Task Execution', desc: 'Agents that work independently.' },
      { title: 'Multi-Agent Systems', desc: 'Teams of agents collaborating.' },
      { title: 'Memory & Context', desc: 'Agents remember and learn.' },
      { title: 'Tool Integration', desc: 'Connect to APIs and databases.' },
      { title: 'Decision Making', desc: 'Intelligent reasoning capabilities.' },
      { title: 'Monitoring Dashboard', desc: 'Track agent activities in real-time.' },
    ],
    techStack: ['AutoGPT', 'CrewAI', 'LangGraph', 'Python', 'OpenAI', 'Vector DBs'],
    process: [
      { step: '01', title: 'Discovery', desc: 'Understanding automation needs.' },
      { step: '02', title: 'Design', desc: 'Planning agent architecture.' },
      { step: '03', title: 'Development', desc: 'Building agent capabilities.' },
      { step: '04', title: 'Training', desc: 'Teaching agents with examples.' },
      { step: '05', title: 'Testing', desc: 'Validating agent performance.' },
      { step: '06', title: 'Deploy', desc: 'Launching autonomous agents.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$2,499', features: ['1 AI Agent', 'Basic Tasks', 'Web Dashboard', '1 Month Support'] },
      { plan: 'Professional', price: '$6,499', features: ['5 AI Agents', 'Multi-Agent System', 'Advanced Tools', 'Memory System', '3 Months Support'] },
      { plan: 'Enterprise', price: '$14,999', features: ['Unlimited Agents', 'Full Customization', 'All Integrations', '24/7 Monitoring', 'Priority Support'] },
    ],
  },
  'data-dashboards': {
    title: 'Data Visualization Dashboards',
    subtitle: 'Real-Time Business Intelligence',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-chart-bar',
    overview: 'I create interactive data visualization dashboards that provide real-time business intelligence insights, helping you make data-driven decisions.',
    features: [
      { title: 'Real-Time Data', desc: 'Live updating dashboards.' },
      { title: 'Custom Charts', desc: 'Tailored visualizations for your data.' },
      { title: 'Interactive Filters', desc: 'Dynamic data exploration.' },
      { title: 'Export Capabilities', desc: 'PDF, Excel, CSV exports.' },
      { title: 'Role-Based Views', desc: 'Different views per user role.' },
      { title: 'Mobile Responsive', desc: 'Dashboards on any device.' },
    ],
    techStack: ['D3.js', 'Chart.js', 'React', 'Node.js', 'SQL', 'WebSocket'],
    process: [
      { step: '01', title: 'Requirements', desc: 'Understanding data needs.' },
      { step: '02', title: 'Design', desc: 'Creating dashboard layouts.' },
      { step: '03', title: 'Data Pipeline', desc: 'Setting up data connections.' },
      { step: '04', title: 'Development', desc: 'Building visualizations.' },
      { step: '05', title: 'Testing', desc: 'Validating data accuracy.' },
      { step: '06', title: 'Deploy', desc: 'Launching with access controls.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$1,499', features: ['5 Charts', 'Basic Dashboard', 'Data Connection', '1 Month Support'] },
      { plan: 'Professional', price: '$3,999', features: ['20 Charts', 'Interactive Filters', 'Real-Time Updates', 'User Roles', '3 Months Support'] },
      { plan: 'Enterprise', price: '$7,999', features: ['Unlimited Charts', 'Full Customization', 'Advanced Analytics', 'API Access', 'Priority Support'] },
    ],
  },
  'excel-automation': {
    title: 'Excel Automation',
    subtitle: 'Advanced Excel Solutions',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-table',
    overview: 'I create advanced Excel solutions with macros, VBA, and Power Query to automate complex data processing tasks and reporting workflows.',
    features: [
      { title: 'VBA Macros', desc: 'Custom automation scripts.' },
      { title: 'Power Query', desc: 'Advanced data transformation.' },
      { title: 'Complex Formulas', desc: 'Advanced Excel calculations.' },
      { title: 'Dashboard Creation', desc: 'Visual reports in Excel.' },
      { title: 'Data Validation', desc: 'Error-proof data entry.' },
      { title: 'Template Design', desc: 'Reusable Excel templates.' },
    ],
    techStack: ['Excel', 'VBA', 'Power Query', 'Power Pivot', 'Macros', 'Data Analysis'],
    process: [
      { step: '01', title: 'Analysis', desc: 'Understanding your Excel needs.' },
      { step: '02', title: 'Design', desc: 'Planning automation structure.' },
      { step: '03', title: 'Development', desc: 'Building macros and queries.' },
      { step: '04', title: 'Testing', desc: 'Validating automation accuracy.' },
      { step: '05', title: 'Documentation', desc: 'Creating user guides.' },
      { step: '06', title: 'Training', desc: 'Teaching your team to use it.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$399', features: ['1 Excel File', 'Basic Macros', 'Simple Formulas', '1 Week Support'] },
      { plan: 'Professional', price: '$999', features: ['5 Excel Files', 'Advanced VBA', 'Power Query', 'Dashboard', '1 Month Support'] },
      { plan: 'Enterprise', price: '$2,499', features: ['Unlimited Files', 'Full Automation', 'Templates', 'Training', 'Priority Support'] },
    ],
  },
  'power-bi': {
    title: 'Power BI Reports',
    subtitle: 'Business Analytics & Reporting',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-chart-pie',
    overview: 'I create comprehensive business reports and analytics dashboards with Power BI, transforming raw data into actionable insights for better decision making.',
    features: [
      { title: 'Interactive Reports', desc: 'Dynamic and drill-down reports.' },
      { title: 'DAX Formulas', desc: 'Advanced calculations and measures.' },
      { title: 'Data Modeling', desc: 'Efficient data relationships.' },
      { title: 'Scheduled Refresh', desc: 'Automatic data updates.' },
      { title: 'Row-Level Security', desc: 'Secure data access control.' },
      { title: 'Embedded Analytics', desc: 'Reports in your applications.' },
    ],
    techStack: ['Power BI', 'DAX', 'SQL', 'Power Query', 'Azure', 'Data Modeling'],
    process: [
      { step: '01', title: 'Discovery', desc: 'Understanding reporting needs.' },
      { step: '02', title: 'Data Prep', desc: 'Cleaning and modeling data.' },
      { step: '03', title: 'Design', desc: 'Creating report layouts.' },
      { step: '04', title: 'Development', desc: 'Building measures and visuals.' },
      { step: '05', title: 'Testing', desc: 'Validating data accuracy.' },
      { step: '06', title: 'Publish', desc: 'Deploying and sharing reports.' },
    ],
    pricing: [
      { plan: 'Starter', price: '$799', features: ['3 Reports', 'Basic Visuals', 'Data Connection', '1 Month Support'] },
      { plan: 'Professional', price: '$1,999', features: ['10 Reports', 'Advanced DAX', 'Scheduled Refresh', 'Row Security', '3 Months Support'] },
      { plan: 'Enterprise', price: '$4,999', features: ['Unlimited Reports', 'Full Analytics Suite', 'Embedded Reports', 'Training', 'Priority Support'] },
    ],
  },
  'data-pipelines': {
    title: 'Data Processing Pipelines',
    subtitle: 'ETL & Data Engineering',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=600&fit=crop',
    icon: 'fa-solid fa-database',
    overview: 'I build ETL pipelines for cleaning, transforming, and analyzing large datasets, ensuring your data is ready for analysis and reporting.',
    features: [
      { title: 'ETL Processes', desc: 'Extract, Transform, Load workflows.' },
      { title: 'Data Cleaning', desc: 'Automated data quality checks.' },
      { title: 'Pipeline Automation', desc: 'Scheduled data processing.' },
      { title: 'Large Datasets', desc: 'Handle millions of records.' },
      { title: 'Error Handling', desc: 'Robust failure recovery.' },
      { title: 'Data Validation', desc: 'Ensure data accuracy and consistency.' },
    ],
    techStack: ['Python', 'Pandas', 'SQL', 'Apache Airflow', 'PostgreSQL', 'AWS'],
    process: [
      { step: '01', title: 'Analysis', desc: 'Understanding data sources.' },
      { step: '02', title: 'Design', desc: 'Planning pipeline architecture.' },
      { step: '03', title: 'Build', desc: 'Creating ETL workflows.' },
      { step: '04', title: 'Test', desc: 'Validating data transformation.' },
      { step: '05', title: 'Automate', desc: 'Scheduling pipeline runs.' },
      { step: '06', title: 'Monitor', desc: 'Tracking pipeline health.' },
    ],
    pricing: [
      { plan: 'Basic', price: '$1,299', features: ['1 Pipeline', 'Basic ETL', 'Data Cleaning', '1 Month Support'] },
      { plan: 'Professional', price: '$3,499', features: ['5 Pipelines', 'Advanced ETL', 'Automation', 'Error Handling', '3 Months Support'] },
      { plan: 'Enterprise', price: '$7,999', features: ['Unlimited Pipelines', 'Full Data Engineering', 'Real-Time Processing', '24/7 Monitoring', 'Priority Support'] },
    ],
  },
};